version: '3'

services:
  node_app:
    container_name: node_app
    build: .
    image: image/node_live_app
    ports:
      - '3000:3000'
    environment:
      PG_DB: postgres
      PG_USER: postgres
      PG_PASSWORD: 1234
      PG_HOST: node_db
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234